substitutions:
  _REGION: us-central1
  _REPO: autobridge
  _SERVICE: autobridge-api
  _UPLOAD_BUCKET: autobridge-prod-uploads

steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build','-t','${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:${SHORT_SHA}','.']

  - name: gcr.io/cloud-builders/docker
    args: ['push','${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:${SHORT_SHA}']

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -lc
      - |
        gcloud run deploy ${_SERVICE} \
          --image='${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:${SHORT_SHA}' \
          --region='${_REGION}' \
          --allow-unauthenticated \
          --min-instances=1 --max-instances=50 \
          --add-cloudsql-instances="$PROJECT_ID:us-central1:autobridge-mysql" \
          --set-secrets=SPRING_DATASOURCE_USERNAME=autobridge-db-user:latest,SPRING_DATASOURCE_PASSWORD=autobridge-db-pass:latest,JWT_SECRET=jwt-secret:latest,SPRING_MAIL_PASSWORD=smtp-pass:latest \
          --set-env-vars='SPRING_DATASOURCE_URL=jdbc:mysql://127.0.0.1:3306/autobridge,SPRING_MAIL_HOST=smtp.sendgrid.net,SPRING_MAIL_PORT=587,SPRING_MAIL_USERNAME=apikey,SPRING_PROFILES_ACTIVE=prod,AUTOBRIDGE_UPLOAD_DIR=/mnt/gcs/uploads,SPRING_WEB_RESOURCES_STATIC_LOCATIONS=file:/mnt/gcs/uploads/' \
          --add-volume="name=uploads-vol,type=cloud-storage,bucket=${_UPLOAD_BUCKET}" \
          --mount="/mnt/gcs/uploads=uploads-vol"

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:${SHORT_SHA}'
